import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Suspense } from "react";
import Loading from "@/components/Loading";

const outfit = localFont({
  src: [
    {
      path: "./fonts/Outfit-Variable.woff2",
      weight: "100 900",
      style: "normal",
    },
  ],
  variable: "--font-outfit",
  display: "swap",
});

export const metadata: Metadata = {
  title: "PSK Wood Works",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} scroll-smooth scrollbar-custom`}
    >
      <body className="font-sans">
        <Suspense fallback={<Loading />}>{children}</Suspense>
      </body>
    </html>
  );
}
